package jshunter

import "regexp"

// extendedRules is the second wave of curated provider detectors, appended to the
// registry in registerRules(). Every rule here was authored FP-first: a unique
// prefix or a structural validator carries the precision, tight length windows and
// entropy floors gate the tail. Bare hex/base64 shapes with only a nearby brand
// word (Datadog/Cloudflare/Algolia/Mistral/Cohere/Postmark/Resend) were prototyped
// and then deliberately dropped — they flag any coincidental hash near a common
// word, which is exactly the false-positive class this tool exists to avoid. The
// only prefix-less rules that survived carry a structural validator (the database
// connection URI captures + validates the password) or a mandatory brand-context
// gate on a distinctive prefix (Fireworks fw_).
func extendedRules() []Rule {
	return []Rule{
		// ---- Cloud / IaaS / secret managers -------------------------------
		{
			ID:              "azure.storage_account_key",
			Name:            "Azure Storage Account Key",
			Provider:        "Azure",
			SecretType:      "account_key",
			Severity:        SevCritical,
			Pattern:         regexp.MustCompile(`AccountKey=[A-Za-z0-9+/]{86}==`),
			ConfidencePrior: 0.90,
			MinEntropy:      3.5,
			MinLen:          99, MaxLen: 99,
			Validate:   validateAzureStorageKey,
			TPExamples: []string{"Account" + "Key=iv587KE0ZZ+flq6jka8lmb5ZVCx/Oo266LzGN2lCXU1GWy7qMcwxRyb8hxH4HtCpjNj4ILXtB3OJap9erO2rIQ=="},
		},
		{
			ID:              "azure.ad_client_secret",
			Name:            "Azure AD Client Secret",
			Provider:        "Azure",
			SecretType:      "client_secret",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`(?:^|[\x60'"\s>=:(,)])([a-zA-Z0-9_~.]{3}\dQ~[a-zA-Z0-9_~.-]{31,34})(?:$|[\x60'"\s<),])`),
			Group:           1,
			ConfidencePrior: 0.72,
			MinEntropy:      3.2,
			MinLen:          37, MaxLen: 40,
			Validate:   validateAzureADClientSecret,
			TPExamples: []string{"6vF8Q~A" + "SAez41kgnO1GMN9e6Lao0KDJmO1xcYV2W"},
		},
		{
			ID:              "vault.token",
			Name:            "HashiCorp Vault Token",
			Provider:        "HashiCorp",
			SecretType:      "vault_token",
			Severity:        SevCritical,
			Pattern:         regexp.MustCompile(`\bhv[sb]\.[A-Za-z0-9_-]{90,300}`),
			ConfidencePrior: 0.90,
			MinEntropy:      3.5,
			MinLen:          94, MaxLen: 304,
			TPExamples: []string{"hvs.K2F" + "QMsJExyf-tPNQzrJnrL5kgxq-pN9hLG65GvRbendXELD6oN-xzJQl460qJi5Cqx1_oXA00bRsiqBQ6Bjbd73Z5R"},
		},
		{
			ID:              "terraform.cloud_token",
			Name:            "Terraform Cloud Token",
			Provider:        "HashiCorp",
			SecretType:      "api_token",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\b[A-Za-z0-9]{14}\.atlasv1\.[A-Za-z0-9\-_=]{60,70}`),
			ConfidencePrior: 0.95,
			MinEntropy:      3.5,
			MinLen:          83, MaxLen: 93,
			Validate:   validateTerraformToken,
			TPExamples: []string{"n8U9O6i" + "S8LrwRZ.atlasv1.nGyKuoQZzirDplk9yVXw_YoCONm5k45UJFHiyq-IjVkwSmZENoCxvz1hq54kw1eN"},
		},
		{
			ID:              "fly.token",
			Name:            "Fly.io Token",
			Provider:        "Fly.io",
			SecretType:      "api_token",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\b(?:fo1_[A-Za-z0-9_-]{43}|(?:fm1[ar]|fm2)_[A-Za-z0-9+/]{100,500}={0,3})`),
			ConfidencePrior: 0.90,
			MinEntropy:      3.5,
			MinLen:          47, MaxLen: 510,
			TPExamples: []string{"fo1_nPv" + "qf5OcKCsQoZTUQu0gRTIP59e2kXB1_O0lUTkt1nW"},
		},
		{
			ID:              "tailscale.key",
			Name:            "Tailscale Key",
			Provider:        "Tailscale",
			SecretType:      "api_key",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\btskey-(?:auth|api|client|scim|webhook)-[0-9A-Za-z]{8,40}-[0-9A-Za-z]{16,80}\b`),
			ConfidencePrior: 0.90,
			MinEntropy:      3.3,
			MinLen:          32, MaxLen: 140,
			TPExamples: []string{"tskey-a" + "uth-r9CMN39fpoBH7B98-OAIkvj7Ra4K7pPWBiMNzOllak8rni7Qkz5JnovENEXB1"},
		},

		// ---- Version control / CI-CD --------------------------------------
		{
			ID:              "gitlab.runner_token",
			Name:            "GitLab Runner Authentication Token",
			Provider:        "GitLab",
			SecretType:      "runner_token",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bglrt-(?:t\d_[0-9A-Za-z_\-]{27,300}\.[0-9a-z]{9}|[0-9A-Za-z_\-]{20})\b`),
			ConfidencePrior: 0.95,
			MinEntropy:      3.0,
			MinLen:          25, MaxLen: 320,
			Validate:   validateMixedClassToken,
			TPExamples: []string{"glrt-i3" + "E5oiiyHMRUEE7Yvcwp"},
		},
		{
			ID:              "gitlab.agent_token",
			Name:            "GitLab Agent for Kubernetes Token",
			Provider:        "GitLab",
			SecretType:      "agent_token",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bglagent-[0-9A-Za-z_\-]{50}\b`),
			ConfidencePrior: 0.95,
			MinEntropy:      3.2,
			MinLen:          58, MaxLen: 58,
			Validate:   validateMixedClassToken,
			TPExamples: []string{"glagent" + "-iE5uK17OjEJkVTSlD6A5VqiIK26ENxf3jKRxA29WEgeW6ghfyk"},
		},
		{
			ID:              "gitlab.incoming_mail_token",
			Name:            "GitLab Incoming Mail Token",
			Provider:        "GitLab",
			SecretType:      "incoming_mail_token",
			Severity:        SevMedium,
			Pattern:         regexp.MustCompile(`\bglimt-[0-9A-Za-z_\-]{25}\b`),
			ConfidencePrior: 0.95,
			MinEntropy:      3.0,
			MinLen:          31, MaxLen: 31,
			Validate:   validateMixedClassToken,
			TPExamples: []string{"glimt-S" + "g92YzC6xRZJQyKhs3wizTpMj"},
		},
		{
			ID:              "gitlab.scim_oauth_token",
			Name:            "GitLab SCIM OAuth Token",
			Provider:        "GitLab",
			SecretType:      "scim_token",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bglsoat-[0-9A-Za-z_\-]{20}\b`),
			ConfidencePrior: 0.95,
			MinEntropy:      3.0,
			MinLen:          27, MaxLen: 27,
			Validate:   validateMixedClassToken,
			TPExamples: []string{"glsoat-" + "piK355YENsw803rWLqoi"},
		},
		{
			ID:              "docker.hub_pat",
			Name:            "Docker Hub Access Token",
			Provider:        "Docker",
			SecretType:      "access_token",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\b(dckr_pat_[A-Za-z0-9_-]{27}|dckr_oat_[A-Za-z0-9_-]{32})(?:[^A-Za-z0-9_-]|$)`),
			Group:           1,
			ConfidencePrior: 0.95,
			MinEntropy:      3.5,
			MinLen:          36, MaxLen: 41,
			Validate:   validateMixedClassToken,
			TPExamples: []string{"dckr_pa" + "t_fCCWmAhlRgene1R9rr2OUDtVpSs"},
		},
		{
			ID:              "atlassian.api_token",
			Name:            "Atlassian API Token",
			Provider:        "Atlassian",
			SecretType:      "api_token",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bAT[AC]TT3xFfG[A-Za-z0-9+/=_\-]{170,250}`),
			ConfidencePrior: 0.95,
			MinEntropy:      4.0,
			MinLen:          180, MaxLen: 260,
			TPExamples: []string{"ATATT3x" + "FfGF0nQyWNfa9mGDfZoDVc7nbM865A6vGyZy-jlwJDFFAOCf9lWm690Vg9GVvo9VK47EwiRFzvRlsQ5y7LPNdc2Xu7HiMgG6LnticVBvFHJnk9lYp-iyELHliE1TrAetlGBNvMrhDzt1JNJmnPqpNR4Mmi5hZniDJwdUoIxGo4snGsPOcswATyqn4"},
		},
		{
			ID:              "sentry.user_token",
			Name:            "Sentry User Auth Token",
			Provider:        "Sentry",
			SecretType:      "auth_token",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\b(sntryu_[a-f0-9]{64})\b`),
			Group:           1,
			ConfidencePrior: 0.95,
			MinEntropy:      3.0,
			MinLen:          71, MaxLen: 71,
			TPExamples: []string{"sntryu_" + "28d67fddf3303212e93370143bbce401fc27d4ba0aa76bcb0c42fda420700683"},
		},
		{
			ID:              "sentry.org_token",
			Name:            "Sentry Organization Auth Token",
			Provider:        "Sentry",
			SecretType:      "org_auth_token",
			Severity:        SevMedium,
			Pattern:         regexp.MustCompile(`\bsntrys_eyJ[A-Za-z0-9+/]{10,600}={0,2}_[A-Za-z0-9+/]{43}`),
			ConfidencePrior: 0.92,
			MinEntropy:      4.0,
			MinLen:          90, MaxLen: 700,
			Validate:   validateSentryOrgToken,
			TPExamples: []string{"sntrys_" + "eyJpYXQiOiAxNjk5OTk5OTk5LjAsICJ1cmwiOiAiaHR0cHM6Ly9zZW50cnkuaW8iLCAicmVnaW9uX3VybCI6ICJodHRwczovL3VzLnNlbnRyeS5pbyIsICJvcmciOiAiYWNtZSJ9_fFIwbJ3E/k8/EDTUQvO/vTzpQgQ+NQGNTygerAWdpxg"},
		},
		{
			ID:              "circleci.pat",
			Name:            "CircleCI API Token",
			Provider:        "CircleCI",
			SecretType:      "api_token",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bCCIP(?:AT|RJ)_[A-Za-z0-9]{22}_[a-fA-F0-9]{40}\b`),
			ConfidencePrior: 0.95,
			MinEntropy:      3.5,
			MinLen:          70, MaxLen: 70,
			TPExamples: []string{"CCIPAT_" + "PRnCEWSJlLtMBN3yBkttI6_34e1f4365927ffc1da6fe14bacc7a485dfef789b"},
		},
		{
			ID:              "buildkite.api_token",
			Name:            "Buildkite API Access Token",
			Provider:        "Buildkite",
			SecretType:      "api_token",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\b(bkua_[a-z0-9]{40})\b`),
			Group:           1,
			ConfidencePrior: 0.92,
			MinEntropy:      3.2,
			MinLen:          45, MaxLen: 45,
			TPExamples: []string{"bkua_nc" + "9oq9hmh1nc8zw1x3ljknmp15i6bvbjz57cf4mr"},
		},

		// ---- Payments / commerce ------------------------------------------
		{
			ID:              "stripe.webhook_secret",
			Name:            "Stripe Webhook Signing Secret",
			Provider:        "Stripe",
			SecretType:      "webhook_secret",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bwhsec_[A-Za-z0-9]{32,64}\b`),
			ConfidencePrior: 0.90,
			MinEntropy:      3.5,
			MinLen:          38, MaxLen: 70,
			Validate:   validateStripeWebhookSecret,
			TPExamples: []string{"whsec_4" + "Qk9RmZ2pXvL7wYnBt6sHd3JgFa8eCu5Tb1oPq"},
		},
		{
			ID:              "square.access_token",
			Name:            "Square Access Token",
			Provider:        "Square",
			SecretType:      "access_token",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bsq0atp-[0-9A-Za-z_\-]{22}\b`),
			ConfidencePrior: 0.92,
			MinEntropy:      3.0,
			MinLen:          29, MaxLen: 29,
			Validate:   validateSquareToken,
			TPExamples: []string{"sq0atp-" + "7Kd9Rm2QpXvL4wZnYt6BsA"},
		},
		{
			ID:              "square.oauth_secret",
			Name:            "Square OAuth Application Secret",
			Provider:        "Square",
			SecretType:      "oauth_secret",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bsq0csp-[0-9A-Za-z_\-]{43}\b`),
			ConfidencePrior: 0.92,
			MinEntropy:      3.0,
			MinLen:          50, MaxLen: 50,
			Validate:   validateSquareToken,
			TPExamples: []string{"sq0csp-" + "9Xk2Rm7QpVL4wZnYt6BsAdF3gHj5sCe0uTb1oPqNrMz"},
		},
		{
			ID:              "square.application_id",
			Name:            "Square Application ID",
			Provider:        "Square",
			SecretType:      "application_id",
			Severity:        SevInfo,
			Pattern:         regexp.MustCompile(`\bsq0idp-[0-9A-Za-z_\-]{22}\b`),
			ConfidencePrior: 0.90,
			MinEntropy:      3.0,
			MinLen:          29, MaxLen: 29,
			Validate:   validateSquareToken,
			TPExamples: []string{"sq0idp-" + "3Rk9Xm2QpVL4wZnYt6BsAd"},
		},
		{
			ID:              "braintree.access_token",
			Name:            "Braintree Gateway Access Token",
			Provider:        "Braintree",
			SecretType:      "access_token",
			Severity:        SevCritical,
			Pattern:         regexp.MustCompile(`\baccess_token\$(?:production|sandbox)\$[0-9a-z]{16}\$[0-9a-f]{32}\b`),
			ConfidencePrior: 0.97,
			MinEntropy:      3.0,
			MinLen:          70, MaxLen: 73,
			Validate:   validateBraintreeAccessToken,
			TPExamples: []string{"access_" + "token$production$s8f3k2j9d0alq7wp$3f8a9c2e1b7d4a6f5e0c9b8a7d6e5f4c"},
		},
		{
			ID:              "plaid.access_token",
			Name:            "Plaid Access Token",
			Provider:        "Plaid",
			SecretType:      "access_token",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\baccess-(?:sandbox|development|production)-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b`),
			ConfidencePrior: 0.95,
			MinEntropy:      3.0,
			MinLen:          51, MaxLen: 55,
			Validate:   validatePlaidToken,
			TPExamples: []string{"access-" + "production-3a7f2b1c-9d4e-4c8a-b6f5-1e2d3c4b5a69"},
		},

		// ---- AI / LLM providers -------------------------------------------
		{
			ID:              "groq.api_key",
			Name:            "Groq API Key",
			Provider:        "Groq",
			SecretType:      "api_key",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bgsk_[A-Za-z0-9]{52}\b`),
			ConfidencePrior: 0.92,
			MinEntropy:      3.5,
			MinLen:          56, MaxLen: 56,
			TPExamples: []string{"gsk_L2m" + "69I7wDdQGnMo6sFSYnvCeqmkfCXIxmEYupOYzBneBDtnhP0NR"},
		},
		{
			ID:              "perplexity.api_key",
			Name:            "Perplexity API Key",
			Provider:        "Perplexity",
			SecretType:      "api_key",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bpplx-[A-Za-z0-9]{48}\b`),
			ConfidencePrior: 0.90,
			MinEntropy:      3.5,
			MinLen:          53, MaxLen: 53,
			TPExamples: []string{"pplx-jR" + "NwkJTQMlysNBKLcUHINVH44lVYyCoGifZdSlMKC5G1oTHH"},
		},
		{
			ID:              "replicate.api_token",
			Name:            "Replicate API Token",
			Provider:        "Replicate",
			SecretType:      "api_token",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\br8_[A-Za-z0-9]{37}\b`),
			ConfidencePrior: 0.90,
			MinEntropy:      3.5,
			MinLen:          40, MaxLen: 40,
			TPExamples: []string{"r8_TD7U" + "SV0nSe6MVhPyD4v3RhFfioL0bco9gSiMH"},
		},
		{
			ID:              "openrouter.api_key",
			Name:            "OpenRouter API Key",
			Provider:        "OpenRouter",
			SecretType:      "api_key",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bsk-or-v1-[a-f0-9]{64}\b`),
			ConfidencePrior: 0.95,
			MinEntropy:      3.0,
			MinLen:          73, MaxLen: 73,
			TPExamples: []string{"sk-or-v" + "1-067ca04053432ab168ca59d1ee785131358da2b631ef474551c14e56e2142047"},
		},
		{
			ID:              "fireworks.api_key",
			Name:            "Fireworks AI API Key",
			Provider:        "Fireworks",
			SecretType:      "api_key",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bfw_[A-Za-z0-9]{20,48}\b`),
			ConfidencePrior: 0.45,
			RequiresContext: true,
			ContextKeywords: []string{"fireworks"},
			MinEntropy:      3.5,
			MinLen:          23, MaxLen: 51,
			HighFPProne: true,
		},

		// ---- Messaging / email / comms ------------------------------------
		{
			ID:              "telegram.bot_token",
			Name:            "Telegram Bot Token",
			Provider:        "Telegram",
			SecretType:      "bot_token",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`(?:\b|bot)(\d{8,10}:AA[A-Za-z0-9_-]{33})(?:[^A-Za-z0-9_-]|$)`),
			Group:           1,
			ConfidencePrior: 0.90,
			MinEntropy:      3.5,
			MinLen:          44, MaxLen: 46,
			Validate:   validateTelegramBotToken,
			TPExamples: []string{"8172930" + "43:AAF8kQ2vN7pR3wZ1xY6bH0mJ4cL9dT5sG2e"},
		},
		{
			ID:              "intercom.access_token",
			Name:            "Intercom Access Token",
			Provider:        "Intercom",
			SecretType:      "access_token",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bdG9rO[A-Za-z0-9+/]{35,}={0,2}`),
			ConfidencePrior: 0.85,
			MinEntropy:      3.5,
			MinLen:          40, MaxLen: 200,
			HighFPProne: true,
			Validate:    validateIntercomToken,
			TPExamples:  []string{"dG9rOjB" + "hYmMxMmRlM2Y6OWY4ZTdkNmM1YjRhMzkyODE3MDZmZWRjYmE5ODc2NTQ="},
		},

		// ---- SaaS / dev-tools / DB ----------------------------------------
		{
			ID:              "notion.integration_token",
			Name:            "Notion Integration Token",
			Provider:        "Notion",
			SecretType:      "integration_token",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bntn_[0-9]{11}[A-Za-z0-9]{35}\b`),
			ConfidencePrior: 0.95,
			MinEntropy:      3.0,
			MinLen:          50, MaxLen: 50,
			TPExamples: []string{"ntn_985" + "99256546sNwq36XGb0oZ5EgsqW4ZZzvzTqB1WmHdP9K"},
		},
		{
			ID:              "airtable.pat",
			Name:            "Airtable Personal Access Token",
			Provider:        "Airtable",
			SecretType:      "pat",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bpat[A-Za-z0-9]{14}\.[a-f0-9]{64}\b`),
			ConfidencePrior: 0.95,
			MinLen:          82, MaxLen: 82,
			Validate:   validateAirtablePAT,
			TPExamples: []string{"paty2Ur" + "s66mdmQzMj.212d1066396ea0ad7196551fe0fb882415a26e814db1d941ebc26b8664fcd857"},
		},
		{
			ID:              "figma.pat",
			Name:            "Figma Personal Access Token",
			Provider:        "Figma",
			SecretType:      "pat",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bfigd_[A-Za-z0-9_-]{40,64}\b`),
			ConfidencePrior: 0.90,
			MinEntropy:      3.0,
			MinLen:          45, MaxLen: 69,
			TPExamples: []string{"figd_qy" + "Y1U8pFDY3noztcn4wwSjexK6ArKj_xREwZ4OfmG_btqjNTF-lCTS7K_6C"},
		},
		{
			ID:              "postman.api_key",
			Name:            "Postman API Key",
			Provider:        "Postman",
			SecretType:      "api_key",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bPMAK-[0-9a-f]{24}-[0-9a-f]{34}\b`),
			ConfidencePrior: 0.95,
			MinLen:          64, MaxLen: 64,
			Validate:   validatePostmanKey,
			TPExamples: []string{"PMAK-56" + "5771eec9a0db3520965632-5c71d7daef62224b8c00713c8940d9fb1a"},
		},
		{
			ID:              "databricks.pat",
			Name:            "Databricks Personal Access Token",
			Provider:        "Databricks",
			SecretType:      "pat",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bdapi[0-9a-f]{32}(?:-\d)?\b`),
			ConfidencePrior: 0.90,
			MinEntropy:      3.0,
			MinLen:          36, MaxLen: 38,
			TPExamples: []string{"dapi012" + "1bddcf50f562d625d7275d0d93a91"},
		},
		{
			ID:              "planetscale.password",
			Name:            "PlanetScale Database Password",
			Provider:        "PlanetScale",
			SecretType:      "password",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bpscale_pw_[A-Za-z0-9_]{32,64}\b`),
			ConfidencePrior: 0.95,
			MinEntropy:      3.0,
			MinLen:          42, MaxLen: 74,
			TPExamples: []string{"pscale_" + "pw_t4fX0UBxXllV6sNG5iBs8DZshZ_CzZA_pCrn_budFUm"},
		},
		{
			ID:              "planetscale.service_token",
			Name:            "PlanetScale Service Token",
			Provider:        "PlanetScale",
			SecretType:      "service_token",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bpscale_tkn_[A-Za-z0-9_]{32,64}\b`),
			ConfidencePrior: 0.95,
			MinEntropy:      3.0,
			MinLen:          43, MaxLen: 75,
			TPExamples: []string{"pscale_" + "tkn_hncjg9NFd_lr2xXvXCJJGOznaKIMq0QYeVEXnNK0m4e"},
		},
		{
			ID:              "grafana.service_account_token",
			Name:            "Grafana Service Account Token",
			Provider:        "Grafana",
			SecretType:      "service_account_token",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bglsa_[A-Za-z0-9]{32}_[a-f0-9]{8}\b`),
			ConfidencePrior: 0.95,
			MinEntropy:      3.0,
			MinLen:          46, MaxLen: 46,
			TPExamples: []string{"glsa_Rz" + "izFr7ReQJuGwN45JtsKJCqADPyWHTM_2dcc265b"},
		},
		{
			ID:              "newrelic.user_api_key",
			Name:            "New Relic User API Key",
			Provider:        "New Relic",
			SecretType:      "user_api_key",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bNRAK-[A-Z0-9]{27}\b`),
			ConfidencePrior: 0.92,
			MinEntropy:      3.0,
			MinLen:          32, MaxLen: 32,
			TPExamples: []string{"NRAK-N7" + "DPGS9USUSCQ0UVF8R8RCUDI15"},
		},
		{
			ID:              "dropbox.short_lived_token",
			Name:            "Dropbox Short-Lived Access Token",
			Provider:        "Dropbox",
			SecretType:      "access_token",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\bsl\.[A-Za-z0-9_-]{130,152}\b`),
			ConfidencePrior: 0.90,
			MinEntropy:      4.0,
			MinLen:          133, MaxLen: 155,
			TPExamples: []string{"sl.-rVw" + "C4JYxna_05QywxWJhqQgigNMXQs0QPTxs3CmLxx6DNHeTdIDHFDoTrfmmrnyrWEyM32zd5JdAXzirg5WIAho4Dkc9yOsGBdh6k4XDo7zEe9X9jmU8ny713ESrNxrNfdvhV4c"},
		},
		{
			ID:              "rubygems.api_key",
			Name:            "RubyGems API Key",
			Provider:        "RubyGems",
			SecretType:      "api_key",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\brubygems_[a-f0-9]{48}\b`),
			ConfidencePrior: 0.95,
			MinEntropy:      3.0,
			MinLen:          57, MaxLen: 57,
			TPExamples: []string{"rubygem" + "s_a3f9213676dd310470bf162a4a8ae83e93116882474534b8"},
		},

		// ---- Crypto material / connection strings -------------------------
		{
			ID:              "pkcs8.private_key",
			Name:            "PKCS#8 Private Key",
			Provider:        "PKI",
			SecretType:      "private_key",
			Severity:        SevCritical,
			Pattern:         regexp.MustCompile(`-----BEGIN PRIVATE KEY-----`),
			ConfidencePrior: 0.99,
			TPExamples:      []string{"-----BEGIN PRIVATE KEY-----"},
			FPExamples:      []string{"-----BEGIN PUBLIC KEY-----"},
		},
		{
			ID:              "dsa.private_key",
			Name:            "DSA Private Key",
			Provider:        "PKI",
			SecretType:      "private_key",
			Severity:        SevCritical,
			Pattern:         regexp.MustCompile(`-----BEGIN DSA PRIVATE KEY-----`),
			ConfidencePrior: 0.99,
			TPExamples:      []string{"-----BEGIN DSA PRIVATE KEY-----"},
			FPExamples:      []string{"-----BEGIN PUBLIC KEY-----"},
		},
		{
			ID:              "pkcs8.encrypted_private_key",
			Name:            "Encrypted Private Key",
			Provider:        "PKI",
			SecretType:      "private_key",
			Severity:        SevCritical,
			Pattern:         regexp.MustCompile(`-----BEGIN ENCRYPTED PRIVATE KEY-----`),
			ConfidencePrior: 0.99,
			TPExamples:      []string{"-----BEGIN ENCRYPTED PRIVATE KEY-----"},
			FPExamples:      []string{"-----BEGIN PUBLIC KEY-----"},
		},
		{
			ID:              "putty.private_key",
			Name:            "PuTTY Private Key",
			Provider:        "PKI",
			SecretType:      "private_key",
			Severity:        SevCritical,
			Pattern:         regexp.MustCompile(`PuTTY-User-Key-File-\d:`),
			ConfidencePrior: 0.98,
			TPExamples:      []string{"PuTTY-U" + "ser-Key-File-2:"},
			FPExamples:      []string{"PuTTY-U" + "ser-Key-File-Format:"},
		},
		{
			ID:              "db.connection_uri",
			Name:            "Database Connection URI Password",
			Provider:        "Database",
			SecretType:      "db_password",
			Severity:        SevHigh,
			Pattern:         regexp.MustCompile(`\b(?:postgresql|postgres|mysql|mongodb\+srv|mongodb|rediss|redis|amqps|amqp)://[^:@/\s]*:([^@/\s]+)@[a-zA-Z0-9._\-]+`),
			Group:           1,
			ConfidencePrior: 0.55,
			MinLen:          6, MaxLen: 128,
			HighFPProne: true,
			Validate:    validateDBConnURIPassword,
		},
	}
}
